apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - neo4j.yaml
  - vllm.yaml
  - controller.yaml
  - evaporation-cron.yaml
  - ../../otel-collector
  - ../../fluent-bit

labels:
  - pairs:
      app.kubernetes.io/instance: formica
    includeSelectors: true
