apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - neo4j.yaml
  - controller.yaml
  - evaporation-cron.yaml
  - ../../otel-collector/collector.yaml
  - ../../fluent-bit/fluent-bit.yaml

commonLabels:
  app.kubernetes.io/instance: formica
