apiVersion: v1
kind: ServiceAccount
metadata:
  name: formica-controller
  namespace: formica
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: formica-agent
  namespace: formica
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: formica-controller
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: formica-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: formica-controller
subjects:
  - kind: ServiceAccount
    name: formica-controller
    namespace: formica
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: formica-controller-ns
  namespace: formica
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: formica-controller-ns
  namespace: formica
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: formica-controller-ns
subjects:
  - kind: ServiceAccount
    name: formica-controller
    namespace: formica
