apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: formica

resources:
  - ../../base

patches:
  - target: { kind: Deployment, name: formica-controller }
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: dev
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: us-east-1
